#!/bin/sh -e

# Failure means the database already exists.
createdb aikenorganics_test &>/dev/null || true

# Migrate the test database.
foreman run --env=.testenv sequelize db:migrate

# App Tests
foreman run --env=.testenv tape \
  test/home.js \
  test/auth.js
