begin;
  alter table categories alter created_at set default now();
  alter table categories alter updated_at set default now();
  alter table growers alter created_at set default now();
  alter table growers alter updated_at set default now();
  alter table locations alter created_at set default now();
  alter table locations alter updated_at set default now();
  alter table markets alter created_at set default now();
  alter table markets alter updated_at set default now();
  alter table orders alter created_at set default now();
  alter table orders alter updated_at set default now();
  alter table posts alter created_at set default now();
  alter table posts alter updated_at set default now();
  alter table product_orders alter created_at set default now();
  alter table product_orders alter updated_at set default now();
  alter table products alter created_at set default now();
  alter table products alter updated_at set default now();
  alter table user_growers alter created_at set default now();
  alter table user_growers alter updated_at set default now();
  alter table users alter created_at set default now();
  alter table users alter updated_at set default now();
end;
