'use strict'

const test = require('../../test')
const driver = require('../../driver')
const Category = require('../../../db/category')

test('new category', function *(assert) {
  yield driver.signIn('admin@example.com')
  yield driver.visit('/admin/categories/new')
  yield driver.$('#name').sendKeys('Test Category')
  yield driver.$('#position').sendKeys('12345')
  yield driver.$('#meat').click()
  yield driver.$('#meat').submit()
  yield driver.wait(driver.present('#message:not(.active)'))
  const category = yield Category.where({position: 12345}).find()
  assert.is(category.name, 'Test Category')
  assert.is(category.position, 12345)
  assert.is(category.meat, true)
})

test('edit a category', function *(assert) {
  yield driver.signIn('admin@example.com')
  yield driver.visit('/admin/categories/1/edit')
  yield driver.$('#name').clear()
  yield driver.$('#name').sendKeys('Test Name')
  yield driver.$('#position').clear()
  yield driver.$('#position').sendKeys('12345')
  yield driver.$('#meat').click()
  yield driver.$('#meat').submit()
  yield driver.wait(driver.present('#message:not(.active)'))
  const category = yield Category.find(1)
  assert.is(category.name, 'Test Name')
  assert.is(category.position, 12345)
  assert.is(category.meat, true)
})
