'use strict'

const test = require('../../test')
const driver = require('../../driver')
const Category = require('../../../db/category')

test('new category', async (assert) => {
  await driver.signIn('admin@example.com')
  await driver.visit('/admin/categories/new')
  await driver.$('#name').sendKeys('Test Category')
  await driver.$('#position').sendKeys('12345')
  await driver.$('#meat').click()
  await driver.$('#meat').submit()
  await driver.wait(driver.present('#message:not(.active)'))
  const category = await Category.where({position: 12345}).find()
  assert.is(category.name, 'Test Category')
  assert.is(category.position, 12345)
  assert.is(category.meat, true)
})

test('edit a category', async (assert) => {
  await driver.signIn('admin@example.com')
  await driver.visit('/admin/categories/1/edit')
  await driver.$('#name').clear()
  await driver.$('#name').sendKeys('Test Name')
  await driver.$('#position').clear()
  await driver.$('#position').sendKeys('12345')
  await driver.$('#meat').click()
  await driver.$('#meat').submit()
  await driver.wait(driver.present('#message:not(.active)'))
  const category = await Category.find(1)
  assert.is(category.name, 'Test Name')
  assert.is(category.position, 12345)
  assert.is(category.meat, true)
})
